### ISSUE TITLE
Resize images for retina displays

### ISSUE THREAD

**Issue by mjskay** [ggplot2-exts/gallery#101]
Per the discussion with @yutannihilation on #100, I am raising this issue here:

The image instructions ask for an image that "will look good on a retina screen at 350x300 pixels". Such an image would be 700x600 pixels: at twice the width/height resolution retina screens will not need to downsample the image to display at an "effective" pixel size of 350x300; whereas if an image is 350x300 retina screens actually need to upsample the images. Thus 350x300 will not look as good on a retina screen as 700x600 (this issue extends beyond "retina" in the sense of Mac displays to other high-resolution displays, like smartphones).

If the increase in necessary bandwidth is acceptable, probably the simplest solution is to change these lines: 

https://github.com/ggplot2-exts/gallery/blob/f97234e5241a1e1d9a51d197de9fae0b2ad0caa7/scripts/resize-thumbnails.R#L14

https://github.com/ggplot2-exts/gallery/blob/f97234e5241a1e1d9a51d197de9fae0b2ad0caa7/scripts/resize-thumbnails.R#L23

to use 700x600 and then re-generate the thumbnails from the originals. I did that on a separate branch for which I will submit a PR shortly.

**Comment by yutannihilation** [comment]
Thanks for the explanation!

Honestly I think I still don't understand the rules behind here even after reading your comments and googling around some random keywords like "retina display image size." So, let me just trust you and merge your PR.

**Comment by mjskay** [comment]
Cool thanks! Looks better now :).

I think the confusion might be that the `px` unit in HTML/CSS isn't guaranteed to correspond to physical pixels on the screen, despite its name. On high-resolution displays, `1px` might be more than 1 physical pixel. E.g. on retina displays, `1px` = 2 physical pixels. Hence, to display an image without upsampling (which will make it blurry), you need to makes its pixel width and height twice the number of HTML `px` units you want it to appear as on the website. On non-retina displays (where `1px` = 1 physical pixel), the browser can still downsample the larger image to the required size for you.

**Comment by yutannihilation** [comment]
> On non-retina displays (where `1px` = 1 physical pixel), the browser can still downsample the larger image to the required size for you.

Ah, thanks, what I wasn't sure was around this point (e.g. should I add some special media query to the CSS, or should I prepare another image for non-retina displays?). Now it gets a bit clearer to me :)

**Comment by mjskay** [comment]
Ah, makes sense! Yeah, because the element size is manually specified as 350px by 300px, it all just works 🙂.

**Comment by yutannihilation** [comment]
I got it, thanks!
