### ISSUE TITLE
Wrong link for package "ggstats"

### ISSUE THREAD

**Issue by ipuzek** [ggplot2-exts/gallery#189]
Hi, i just noticed that package "ggstats" is not correctly linked, and it ends up on the bottom (with 0 stars) here:

https://exts.ggplot2.tidyverse.org/gallery/

Current link is: "https://github.com/larmarange/ggstat/"
...and it should be: "https://github.com/larmarange/ggstats"

That's it, best,
Ivan

**Comment by yutannihilation** [comment]
Thanks!
