### ISSUE TITLE
Use GitHub Action to update github_meta.json

### ISSUE THREAD

**Issue by yutannihilation** [ggplot2-exts/gallery#61]
Currently, the counts of stars are manually updated. Can we do it by GitHub Action?

**Comment by thomas-neitmann** [comment]
I think you can setup CRON jobs on GitHub actions so you could for example update once a day.

**Comment by yutannihilation** [comment]
Yeah, I think so too.

**Comment by thomas-neitmann** [comment]
I found [this](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule) helpful section in the documentation.
