### ISSUE TITLE
How do you build this site

### ISSUE THREAD

**Issue by steve-liang** [ggplot2-exts/gallery#84]
want to steal your work and build my own gallery with similar layout locally. Can you show me how the gallery site is built?

**Comment by yutannihilation** [comment]
Honestly I don't understand the whole picture of this repo, but probably something like

The widgets in [`_config.yml`](https://github.com/ggplot2-exts/gallery/blob/61c4470a5a6c35a6ab8184441edaf7ee5359cfac/_config.yml#L9) are inserted into [HTML template](https://github.com/ggplot2-exts/gallery/blob/gh-pages/_layouts/default.html#L97-L128) and styled by some [CSS](https://github.com/ggplot2-exts/gallery/tree/gh-pages/css) and [JavaScript](https://github.com/ggplot2-exts/gallery/blob/gh-pages/js/grid.js).

Wish you a luck on your project!
