### ISSUE TITLE
server IP address could not be found

### ISSUE THREAD

**Issue by IndrajeetPatil** [ggplot2-exts/gallery#87]
At https://www.ggplot2-exts.org/gallery/, I see the following:

![image](https://user-images.githubusercontent.com/11330453/76462079-5bf81d80-63e1-11ea-9ffc-d2f9a5ef8a58.png)

**Comment by yutannihilation** [comment]
@Emaasit Do you know something wrong with the domain registration?

**Comment by sctyner** [comment]
Hello, I am also having problems. In Chrome I get the following error: ERR_TUNNEL_CONNECTION_FAILED. In Safari, the error is "Safari cannot open the page because the server cannot be found." In Firefox, the error is, "Firefox can’t establish a connection to the server at www.ggplot2-exts.org."

**Comment by Emaasit** [comment]
Oh yes. Looks like the domain name expired. I'll try to re-purchase it when it's available in circulation

**Comment by hadley** [comment]
Would you prefer something like `exts.ggplot2.tidyverse.org`?

**Comment by Emaasit** [comment]
@hadley Yes, that would be perfect.

**Comment by hadley** [comment]
Ok, just set it up, so you should be able to set that as your CNAME for github pages now. I'd appreciate it if you'd make me an admin of this repo, so I can step in as needed in the future. Thanks!

**Comment by yutannihilation** [comment]
Seems I have the permission, so I set it on https://github.com/ggplot2-exts/ggplot2-exts.github.io/settings. `https://` URL is not available at the moment, but http://exts.ggplot2.tidyverse.org/gallery/ works already!

**Comment by IndrajeetPatil** [comment]
Closing this as http://exts.ggplot2.tidyverse.org/gallery/ seems to be working.

**Comment by barthoekstra** [comment]
As the original url is _still_ down, shouldn't this be changed on the ggplot docs as well? Took me many attempts over multiple weeks before I figured out — through this issue here — that the gallery can be accessed through a different url now.

At least I'm glad to see the gallery still exists :-)
