### ISSUE TITLE
Update website at top of GitHub page

### ISSUE THREAD

**Issue by aosmith16** [ggplot2-exts/gallery#90]
The website listed at the top of the GitHub repo hasn't been updated to the new website yet.  It still says `Gallery of ggplot2 extensions https://www.ggplot2-exts.org/gallery/`.

I tried doing a pull request but it looks like editing the GitHub page itself isn't actually detected as a change. :woman_shrugging:

**Comment by IndrajeetPatil** [comment]
For those who might come across this, the working link now is:
http://exts.ggplot2.tidyverse.org/gallery/

**Comment by yutannihilation** [comment]
Good catch, I fixed this yesterday. Thanks for the notice!
