### ISSUE TITLE
Gallerly does not show all entries

### ISSUE THREAD

**Issue by thomas-neitmann** [ggplot2-exts/gallery#98]
When I open the gallery it says "Showing 55 of 72" but there is nothing like a "Show next page" button. After entering something in the "Text Filter" field and removing it, the site suddenly shows all 72 packages. This seems like a bug to me.

**Comment by yutannihilation** [comment]
You can turn off "CRAN only" to show all the packages :)

![Screenshot from 2020-05-26 22-02-24](https://user-images.githubusercontent.com/1978793/82903982-c3634980-9f9c-11ea-8224-7e9e6559b1a1.png)

**Comment by thomas-neitmann** [comment]
That explains why you can see only 55 entries when you open the site. But after entering and deleting something in the "Text Filter" field all entries are shown because the "CRAN only" toggle bar turns off. Is this really expected behavior?

**Comment by yutannihilation** [comment]
Oh, I don't think it's expected. Feel free to contribute.
